version: '3.8'

services:
  openvpn-client:
    container_name: openvpn-client
    image: localhost:5000/airvpn-hummingbird
    cap_add:
      - net_admin
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    stop_grace_period: 120s
    devices:
      - /dev/net/tun
    tmpfs:
      - /run
      - /tmp
      - /etc/airvpn
    volumes:
      - ./openvpn-client/:/vpn

networks:
  default:
    name: airvpn_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
